name: json_schema
version: 2.2.2
description: Provide support for validating instances against json schema
authors:
  - Michael Carter <michael.carter@workiva.com>
  - Daniel Davidson <dbdavidson@yahoo.com>
homepage: https://github.com/workiva/json_schema

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  args: ">=0.13.7 <2.0.0"
  collection: ^1.14.6
  logging: ">=0.9.3 <0.12.0"
  path: ^1.3.0
  uri: ">=0.11.1 <0.12.0"

dev_dependencies:
  build_runner: ^1.7.1
  build_test: ^0.10.9
  dart_dev: ^2.0.0
  dart_style: ^1.3.1
  dependency_validator: ^1.4.0
  shelf: ^0.7.2
  shelf_static: ^0.2.7
  test: ^1.9.1
