name: json_schema
version: 2.2.2
description: Provide support for validating instances against json schema
authors:
  - Michael Carter <michael.carter@workiva.com>
  - Daniel Davidson <dbdavidson@yahoo.com>
homepage: https://github.com/workiva/json_schema

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  collection: ^1.15.0
  logging: ^1.0.1
  path: ^1.8.0
  uri: ^1.0.0

dev_dependencies:
  build_runner:
  build_test:
  dart_dev:
  dart_style:
  shelf:
  shelf_static:
  test:
